apiVersion: v1
kind: Service
metadata:
  name: ueransim-phone
  labels:
    app.kubernetes.io/name: ueransim-phone
spec:
  type: ClusterIP
  selector:
    app: ueransim
    component: ue
  ports:
    - name: https
      port: 443
      targetPort: phone-https
      protocol: TCP
